plugins {
    alias(libs.plugins.android.library)
}

group = 'com.fanvil.link'
version = '0.0.7'

android {
    namespace "com.fanvil.link.sdk"
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        minSdk 24
        targetSdk 36
        consumerProguardFiles 'consumer-rules.pro'
        externalNativeBuild {
            cmake {
                abiFilters 'armeabi-v7a', 'arm64-v8a'
                cppFlags '-g', '-Wl,-z,max-page-size=16384'
            }
        }
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
        }
    }
}

base {
    archivesName = "fv_cloud_talk-sdk-${project.version}"
}

dependencies {
    api files('libs/org.eclipse.paho.mqttv5.client-1.2.5.jar')
    // AGP 禁止 library 直接 api/implementation 本地 .aar；编译期可见，运行期由宿主工程提供
    compileOnly files('libs/linphone-sdk-android-0.0.12-release.aar')
    api('com.smart.rinoiot:rinoPanel:1.2.1') {
        exclude module: 'common-log'
        exclude module: 'common-res'
        exclude module: 'rinoReactNative'
        exclude module: 'rinoReactNativeV8'
        exclude module: 'rinoReactFastImage'
        exclude module: 'rinoReactReanimated'
        exclude module: 'rinoReactGesture'
        exclude module: 'rinoReactScreens'
        exclude module: 'rinoReactSafeArea'
        exclude module: 'rinoReactSvg'
        exclude module: 'rinoReactAsyncStorage'
        exclude module: 'rinoReactCommunityBlur'
        exclude module: 'rinoReactCommunityMaskedView'
        exclude module: 'rinoReactCropPicker'
        exclude module: 'rinoReactPagerView'
        exclude module: 'rinoReactPicker'
        exclude module: 'rinoReactVideo'
        exclude module: 'rinoReactWebview'
        exclude module: 'rinoReactLottiee'
        exclude module: 'rinoReactFfmpeg'
        exclude module: 'rinoMatterSdk'
        exclude group: 'com.linecorp.linesdk', module: 'linesdk'
        exclude group: 'com.github.adityaxjha', module: 'Android-ScalableVideoView'
        exclude group: 'com.github.yalantis', module: 'ucrop'
        exclude group: 'com.github.Dimezis', module: 'BlurView'
        exclude group: 'com.android.support'
    }
}
